name: Crear rama
on:
  push:
    branches:
      - 'master'
      - 'releases/**'
jobs:
  job1:
    name: Crear rama release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Crear rama release
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'release'  