name: Crear rama
on:
  push:
    branches: [ master ]
jobs:
  job1:
    name: Crear rama release
    runs-on: ubuntu-latestest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Crear rama release
      run:
        git checkout -b release
        git push -f -u origin release

