name: Crear rama
on:
  push:
    branches:
      - 'master'
      - 'releases/**'
jobs:
  job1:
    name: Crear rama release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Crear rama release
      run:
        git checkout -b release
        git push -f -u origin release
    - name: MErge main --> release
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${( secrets_GITHUB_TOKEN )}
        source-branch: main
        target-branch: release    