name: create PR

on:
  push:
    branches:
      - 'feature/**'


jobs:
  develop:
    name: Create PR Feature to Develop
    if: contains(github.event.head_commit.message, '[MERGE2DEVELOP]') ||
        contains(github.event.head_commit.message, '[MERGE2DEV]')
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        if: ${{ env.GITHUB_ACTOR == 'gromeron-mock' }}
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: [develop]
          pr_title: "[Automated] Merge ${{ github.ref_name }} into develop"
          pr_body: "Automated Pull Request"